/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'brand-dark': '#090909',
        'brand-border': '#2A2A2A',
        'level-0': '#090909',
        'level-1': '#101010',
        'level-2': '#151515',
        'border-color': '#2A2A2A',
        'border-subtle': '#2A2A2A',
        'panel-bg': '#101010',
        'primary': '#ffffff',
        'on-primary': '#2f3131',
        'secondary': '#c7c6c6',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c7c8',
        'outline': '#8e9192',
        'outline-variant': '#444748',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'accent-cyan': '#80DEEA',
        'accent-green': '#A5D6A7',
        'accent-blue': '#90CAF9',
        'accent-coral': '#EF9A9A',
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        'margin-desktop': '32px',
        'margin-mobile': '16px',
        'stack-lg': '32px',
        'stack-md': '16px',
        'stack-sm': '8px',
        'gutter': '1px',
        'unit': '4px',
      },
      fontFamily: {
        'space-mono': ['Space Mono', 'monospace'],
        'jetbrains-mono': ['JetBrains Mono', 'monospace'],
        'body-md': ['Space Mono', 'monospace'],
        'body-lg': ['Space Mono', 'monospace'],
        'mono-data': ['Space Mono', 'monospace'],
        'headline-md': ['Space Mono', 'monospace'],
        'display-lg': ['Space Mono', 'monospace'],
        'label-sm': ['Space Mono', 'monospace'],
        'headline-lg': ['Space Mono', 'monospace'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.0', letterSpacing: '0.08em', fontWeight: '400' }],
        'mono-data': ['13px', { lineHeight: '1.4', letterSpacing: '-0.02em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['18px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '700' }],
        'display-lg': ['40px', { lineHeight: '1.1', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
